services:
  kong-database:
    image: kong:3.0.0-alpine
    container_name: kong-database
    environment:
      - KONG_DATABASE=off
    networks:
      - kong-network
    volumes:
      - kong-data:/var/lib/kong

  kong:
    image: kong:3.0.0-alpine
    container_name: kong
    environment:
      - KONG_DATABASE=off
      - KONG_ADMIN_LISTEN=0.0.0.0:8001
      - KONG_DECLARATIVE_CONFIG=/usr/local/kong/kong.yml
    ports:
      - "8000:8000"   # HTTP port for API traffic
      - "8001:8001"   # Admin API
    networks:
      - kong-network
    depends_on:
      - kong-database
    volumes:
      - ./kong-config/kong.yml:/usr/local/kong/kong.yml

  nextjs1:
    build:
      context: ./nextjs1
    container_name: nextjs1
    networks:
      - kong-network
    expose:
      - "3002"
  
  nextjs2:
    build:
      context: ./nextjs2
    container_name: nextjs2
    networks:
      - kong-network
    expose:
      - "3003"
    
  backend:
    build:
      context: ./backend
    container_name: backend
    networks:
      - kong-network
    expose:
      - "3333"
    
networks:
  kong-network:
    driver: bridge

volumes:
  kong-data:
